In [1]:
import numpy as np
import pandas as pd

from PIL import Image
import glob
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
img = Image.open('train/indoor/3.jpg')

In [3]:
np.asarray(img)[:,:,0]

array([[ 30,  30,  30, ..., 105, 114, 111],
       [ 30,  30,  30, ..., 100, 110, 108],
       [ 30,  30,  30, ...,  99, 103,  96],
       ...,
       [175, 167, 170, ..., 119,  96,  96],
       [175, 167, 170, ..., 106, 124, 124],
       [175, 167, 170, ..., 168, 172, 172]], dtype=uint8)

In [4]:
filenames1 = glob.glob("train\\indoor\\*")

In [5]:
lst1 = []
for file in filenames1:
    try:
        img = Image.open(file)

        res = pd.DataFrame(np.asarray(img).reshape(3,-1).T).describe().values.reshape(-1).tolist()[3:-3]
        res.append(1)


        lst1.append(res)
    except:
        print(file+'error')

train\indoor\18854.jpgerror

In [ ]:
lst1

In [6]:
filenames0 = glob.glob("train\\outdoor\\*")

In [29]:
lst0 = []
for file in filenames0:
    try:
        img = Image.open(file)

        res = pd.DataFrame(np.asarray(img).reshape(3,-1).T).describe().values.reshape(-1).tolist()[3:-3]
        res.append(0)


        lst0.append(res)
        
    except:
        print(file+'error')

train\outdoor\19433.jpgerror
train\outdoor\63998.jpgerror

In [30]:
df0 = pd.DataFrame(lst0)
df1 = pd.DataFrame(lst1)

In [31]:
df = df0.append(df1)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,162.537333,128.822800,54.045467,49.207745,61.928861,31.734735,0.0,4.0,0.0,134.75,72.0,32.0,174.5,146.0,46.0,194.00,177.0,68.0,0
1,181.775333,116.444400,125.921467,39.818053,52.216703,40.976777,46.0,0.0,0.0,159.00,90.0,91.0,189.0,126.0,135.0,212.00,160.0,160.0,0
2,209.209107,120.659643,101.827500,61.349432,53.606898,16.211141,17.0,5.0,24.0,206.00,88.0,92.0,234.0,106.0,104.0,247.00,134.0,113.0,0
3,38.074933,50.240667,117.352133,30.598597,40.167181,66.971857,0.0,0.0,0.0,19.00,27.0,63.0,31.0,42.0,95.0,49.00,59.0,165.0,0
4,156.722125,139.264500,130.619750,52.395874,58.774192,57.815063,7.0,0.0,0.0,130.00,88.0,79.0,162.0,145.0,136.0,191.00,182.0,170.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28100,180.259467,90.769333,99.053333,37.531352,47.295945,47.387616,39.0,0.0,0.0,159.00,55.0,56.0,187.0,83.0,106.0,208.00,124.0,141.0,1
28101,156.815352,99.290141,64.878028,62.200926,62.864910,47.691545,0.0,0.0,0.0,109.00,47.0,32.0,154.0,78.0,49.0,204.25,156.0,77.0,1
28102,147.792712,93.345254,49.836780,76.671288,58.484722,45.309955,0.0,0.0,0.0,65.00,37.0,15.0,189.0,92.0,25.0,216.00,148.0,86.0,1
28103,147.999067,128.841467,136.376000,31.657195,34.533862,23.029054,13.0,21.0,13.0,130.00,105.0,122.0,161.0,130.0,134.0,170.00,149.0,151.0,1
28104,95.123467,124.712133,113.142267,61.348410,49.286783,60.890532,0.0,0.0,0.0,45.00,88.0,58.0,85.0,123.0,121.0,133.00,163.0,155.0,1

In [37]:
array = df.values
X = array[:,0:18]
Y = array[:,18]
test_size = 0.33
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=test_size, random_state=seed)

In [38]:
model = LogisticRegression()

In [39]:
model.fit(X_train, Y_train)

c:\program files\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [40]:
result = model.score(X_test, Y_test)

In [41]:
print('Accuracy: %.3f%%' %(result*100))

Accuracy: 71.188%